if type -q git
    if status is-interactive
        abbr --add --global -- ga 'git add'
        abbr --add --global -- gaa 'git add --all'
        abbr --add --global -- gb 'git branch'
        abbr --add --global -- gbd 'git branch --delete --force'
        abbr --add --global -- gcfd 'git clean -fd'
        abbr --add --global -- gcm 'git commit -m'
        abbr --add --global -- gcma 'git commit --amend --no-edit'
        abbr --add --global -- gcmf 'git commit --fixup'
        abbr --add --global -- gco 'git checkout'
        abbr --add --global -- gcob 'git checkout -b'
        abbr --add --global -- glol 'git log --graph --decorate --pretty=oneline --abbrev-commit --topo-order'
        abbr --add --global -- glola 'git log --graph --decorate --pretty=oneline --abbrev-commit --topo-order --all'
        abbr --add --global -- gm 'git merge --no-ff'
        abbr --add --global -- gpl 'git pull'
        abbr --add --global -- gplom 'git pull origin main'
        abbr --add --global -- gpr 'git reset --hard'
        abbr --add --global -- gps 'git push'
        abbr --add --global -- gpsf 'git push --force'
        abbr --add --global -- gpt 'git push --tags'
        abbr --add --global -- gri 'git rebase --interactive HEAD'
        abbr --add --global -- gs 'git status --short'
    end
end
